# 此工作流将对Pull Request进行分类，并根据
# Pull Request中修改的文件路径应用标签。
#
# 要使用此工作流，您需要设置一个.github/labeler.yml
# 文件进行配置。更多信息，请参阅：
# https://github.com/actions/labeler

name: 自动标签器
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"