name: 自动总结新issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 运行AI推理
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            请用一段话总结以下GitHub issue:
            标题: ${{ github.event.issue.title }}
            内容: ${{ github.event.issue.body }}

      - name: 以AI总结内容评论
        run: |
          gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.response }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          RESPONSE: ${{ steps.inference.outputs.response }}